### ISSUE TITLE
`jectl mount` fails with a persistent dataset

### ISSUE THREAD

**Issue by Subito** [KlaraSystems/jectl#2]
```
root@files10:~ # zfs create -o mountpoint=/usr/jails/nginxtest/usr/local/www zroot/JAIL/nginxtest/default/sites
root@files10:~ # zfs list -r zroot/JE zroot/JAIL
NAME                                  USED  AVAIL     REFER  MOUNTPOINT
zroot/JAIL                            873M   469G       96K  none
zroot/JAIL/jectl.eC9wml                96K   469G       96K  none
zroot/JAIL/nginxtest                  872M   469G       96K  none
zroot/JAIL/nginxtest/default          872M   469G      872M  /usr/jails/nginxtest
zroot/JAIL/nginxtest/default/config   164K   469G      100K  /usr/jails/nginxtest/config
zroot/JAIL/nginxtest/default/sites     96K   469G       96K  /usr/jails/nginxtest/usr/local/www
zroot/JE                               96K   469G       96K  none
root@files10:~ # service jail restart nginxtest
Stopping jails:.
Starting jails: cannot start jail  "nginxtest":
cannot unmount '/usr/jails/nginxtest': unmount failed
jail: nginxtest: jectl mount nginxtest /usr/jails/nginxtest: failed
.
```
I assumed that `default` was synonym to the JE-Name used here: https://github.com/KlaraSystems/jectl/blob/main/overview-zfs-layout.txt#L37

**Comment by rob-wing** [comment]
This is likely from setting the mountpoint directly on zroot/JAIL/nginxtest/default/sites.

jectl wants child datasets to inherit the mountpoint from zroot/JAIL/nginxtest/default. When you set the mountpoint directly on the child dataset, jectl will not try to unmount it and therefore will fail trying to unmount the parent dataset (i.e., zroot/JAIL/nginxtest/default).

**Comment by Subito** [comment]
Perfect, that works! Just `zfs create zroot/JAIL/nginxtest/default/sites` works as expected. Is there a way to influence the mountpoint if I want to e.g mount something to `/usr/local/www` or do I need to create `zroot/JAIL/nginxtest/default/usr/local/www`?

**Comment by rob-wing** [comment]
The way jectl handles this right now, you would have to do the latter:

`zfs create -p zroot/JAIL/nginxtest/default/usr/local/www`.

Although, this may not work as expected because now the jail environment /usr will be covered up by the zfs dataset. In general, I'd recommend naming the persistent datasets such that they don't clash with the standard filesystem layout.

For this example, would it be possible to use /sites within the jail instead of /usr/local/www?

**Comment by Subito** [comment]
yes, thats no problem. Thanks for clarifying!
