### ISSUE TITLE
Not clear how to inject config files into `/config` at build time

### ISSUE THREAD

**Issue by Subito** [KlaraSystems/jectl#4]
For example I would like a prepared `/etc/resolv.conf` injected/build into the config dataset. The overlay-directory mechanism of `poudriere image` does not seem to satisfy this use case.`-c overlaydir` (as used here: https://github.com/KlaraSystems/jectl/blob/main/overview-generate-je.txt#L60) is mounting the overlaydir into the image at creation-time which writes e.g the `mater.passwd` to the config-dataset if a symlink pointing to it is present in the overlay-dir.

**Comment by rob-wing** [comment]
If I understand correctly, you'd place the prepared `/etc/resolv.conf` in the overlay directory instead of symbolic link; something like:

```
% mkdir /home/rew/overlay
% cd /home/rew/overlay
% mkdir etc
% mv prepared-resolv.conf etc/resolv.conf
```

Let me know if I misunderstood or if that doesn't work as expected.

**Comment by Subito** [comment]
Perfect, that was a misunderstanding on my part. I had problems to grasp how the overlay-dir works, but it makes way more sense now, thanks!
